version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/api
      - /api/node_modules
    ports:
      - 8800:8800
      - 9229:9229
    command: yarn start:dev
    restart: always