name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create env file
      run: |
          cat << EOF > .production.env
          PORT=${{ secrets.PORT }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          FORGOT_PASSWORD_SECRET=${{ secrets.FORGOT_PASSWORD_SECRET }}
          CLIENT_URL=${{ secrets.CLIENT_URL }}
          SECURE=${{ secrets.SECURE }}
          DOMAIN=${{ secrets.DOMAIN }}
          EOF
    - run: yarn install
    - run: yarn build
    - run: pm2 reload api-new
    
