name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create env file
      run: |
          touch .production.env
          echo PORT=${{ secrets.PORT }}" >> .env
          echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo FORGOT_PASSWORD_SECRET=${{ secrets.FORGOT_PASSWORD_SECRET }} >> .env
          echo CLIENT_URL=${{ secrets.CLIENT_URL }} >> .env
          echo SECURE=${{ secrets.SECURE }} >> .env
          echo DOMAIN=${{ secrets.DOMAIN }} >> .env
          cat .production.env
    - run: yarn install
    - run: yarn build
    - run: pm2 reload api-new
    
